version: '3.8'

services:
  ingestion:
    build:
      context: ./src/ingestion
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app

  interaction:
    build:
      context: ./src/interaction
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
